#!/bin/bash

export RPC_PORT=XXXX # Electrumx RPC command port, different than Electrad port (5788)
export CACHE_MB=1200

export COIN=Electra
export DB_DIRECTORY=~/.electrumx/eca

#127.0.0.1 for local Daemon, change the IP for a remote Daemon:
export DAEMON_URL=http://RPCuser:RPCpass@127.0.0.1:5788 

export NET=mainnet
export DB_ENGINE=leveldb

#keep this empty:
export HOST= 

export RPC_HOST=127.0.0.1
export TCP_PORT=50001
export SSL_PORT=50002
export SSL_CERTFILE=~/.electrumx/server.crt
export SSL_KEYFILE=~/.electrumx/server.key
export BANNER_FILE=~/.electrumx/banner_file.txt
export DONATION_ADDRESS=EQga7kDDjdKM9aYPtuRjoH5uZJdu4GMJDi

# run electrumx
ulimit -n 10000
echo "Starting ElectrumX, logging to ~/.electrumx/electrumx.log"
~/electrumx/electrumx_server >> ~/.electrumx/electrumx.log 2>> ~/.electrumx/electrumx.log